name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        xcode-version: '13.2.1'

    - name: Build and test
      run: xcodebuild clean build test -project PriceComparator.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
